version: '3'
services:
  upload_server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image:
      eventbox-upload:v1
    env_file: 
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: always
    command: yarn start